# Recommended install command: (can substitute conda for mamba)
# conda env create -p ./.venv --file conda.dev.env.yaml
# Recommended update command: (can substitute conda for mamba)
# conda env update -p ./.venv --file conda.dev.env.yaml
name:
channels:
  - conda-forge # location for more needed packages
  - fastai # location of nbdev libraries
  - bioconda # location of most bioinformatic tools
dependencies:
  - python=3.11
  - ca-certificates
  - openssl
  - ipykernel # for integration with notebooks
  - nbdev=2.3.34 # Using nbdev framework, required conda to install for myself and couldn't use mamba
  - pip # for installing python packages
  - quarto # used in nbdev for doc generation
  - jupyterlab # used by quarto
  - pandas # used by quarto
  - matplotlib # used by quarto for plotting
  - gh # used in nbdev for doc generation and github integration
  - twine # for pypi deployments
  - anaconda-client # for anaconda deployments
  - conda-build # for conda deployments
  # Standard libraries used in our code development
  - python-dotenv # for loading environment variables from .env file
  - pip:
      - envyaml # for loading environment variables into variables with a .yaml file
      - black # for code formatting
      - flake8 # for code formatting
# Additional programs for specific development follow
  - pydantic
  - uvicorn
  - fastapi